services:
  web:
    build: .
    env_file:
      - .env
    environment:
      OPENWEATHERMAP_API_KEY: "05837f62afa880aa9c2b90ef1b987f48"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
