services:
  web:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
